### PR TITLE
Performance and behavioural changes to support autoscaling a bit nicer

### PR DESCRIPTION
**Pull request by tractorcow**
Hi @wilr, I realise this PR is highly opinionated, but I thought it'd be polite to share my WIP for a project I've been doing.

A couple of explanations for what I've done:
 - I shifted the protected asset urls to SAS signed urls; This takes the load off the PHP server back to Azure.
 - I shifted the local storage cache into a DB cache; This is because if you are running a site with a LOT of images, breaking the cache can be a very expensive problem (fopen() fails a LOT if you try to hydrate a dead cache). Also, when you are autoscaling, you don't want your new nodes scaling into a broken state.
 - Bumped up the CMS dependency to 4.8, because bust_cache is only present there, and SAS urls don't work without that fix.
 - I removed the local file storage for tinymce, because frankly, that assumes you have/want a local filesystem, and are not scaling, which kind of defeats the purpose of running something like Azure storage.

### CODE REVIEW

**Comment by wilr** [comment]
Nice! all valid points, our project didn't use autoscaling so didn't get to jump through those hoops - maybe next time! 

Let me know when your WIP is finished up and ready for merge.

**Comment by tractorcow** [comment]
Running a deployment later today to test out the recent fixes in Azure. :)

**Comment by tractorcow** [comment]
Testing worked well; I have nice protected images with SAS urls running fine, and my next.js SPA managed to access a large number of images during build time without crashing (which the db cache addresses).

**Comment by wilr** [comment]
Epic! thanks tagged a new release with the change.

**Pull request merged**
